channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - boto3
  - botocore
  - uwsgi
  - beautifulsoup4
  - flask
  - flake8
  - isort
  - nltk
  - numpy
  - pandas
  - psycopg2
  - pytz
  - python==3.7
  - pyyaml==3.13
  - sqlalchemy
  - tqdm
  - urllib3
  - pytorch==0.4.1
  - pip:
    - ansible
    - awscli
    - flask-sqlalchemy
    - janome
    - jsonlines
    - mojimoji==0.0.8
    - psycopg2-binary
    - pypugjs
    - s3transfer
    - toml
    - torchtext==0.3.1
