channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - boto3
  - botocore
  - uwsgi
  - beautifulsoup4
  - flask
  - nltk
  - numpy
  - pandas
  - psycopg2
  - pytz
  - pyyaml=3.13
  - urllib3
  - pytorch=0.4.1
  - pip:
    - ansible
    - awscli
    - flask-sqlalchemy
    - janome
    - jsonlines
    - mojimoji
    - psycopg2-binary
    - pypugjs
    - s3transfer
    - sqlalchemy
    - toml
    - torchtext
    - tqdm
