version: 2
jobs:
  build:
    docker:
      - image: pecorarista/market-reporter
        user: reporter
    steps:
      - checkout
      - run:
          name: Print the working directory
          command: pwd
      - run:
          name: Show who I am
          command: whoami
      - restore_cache:
          keys:
            - market-reporter-{{ checksum "environment-fixed.yaml" }}
      - run:
          name: Create an environment
          command: |
              conda env create -f environment-fixed.yaml -n circleci --quiet
      - save_cache:
          key: market-reporter-{{ checksum "environment-fixed.yaml" }}
          paths:
            - /opt/conda
            - /opt/reporter/.conda
      - run:
          name: Activate an environment
          command: |
              source /opt/conda/etc/profile.d/conda.sh
              conda activate circleci
      - run:
          name: Check formats
          command: flake8
      - run:
          name: Run unit tests
          command: python setup.py test
