version: 2
jobs:
  build:
    docker:
      - image: pecorarista/pipenv
        user: circleci
      - image: postgres:10
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test_db
    steps:
      - checkout
      - restore_cache:
          keys:
            - market-reporter-{{ checksum "Pipfile.lock" }}
      - run:
          name: Create an environment
          command: pipenv sync --dev
          environment:
            PIPENV_VENV_IN_PROJECT: 1
      - save_cache:
          key: market-reporter-{{ checksum "Pipfile.lock" }}
          paths:
            - /home/circleci/project/.venv
            - /home/circleci/.cache/pipenv
      - run:
          name: Create `config.toml`
          command: |
            cat example.toml \
            | sed -e "s#^uri = 'postgresql://ubuntu@localhost:5432/DBNAME'\$#uri = 'postgresql://circleci@localhost:5432/test_db'#" \
            | sed -e "s#^uri = 'postgresql://ubuntu@localhost:5432/TESTDBNAME'\$#uri = 'postgresql://circleci@localhost:5432/test_db'#" \
            | tee config.toml
      - run:
          name: Check formats
          command: |
            pipenv run flake8 mypkg tests
            pipenv run isort --recursive --check-only mypkg tests
      - run:
          name: Run unit tests
          command: |
            pipenv run pytest
