version: 2
jobs:
  build:
    docker:
      - image: pecorarista/market-reporter
        user: reporter
    steps:
      - checkout
      - run:
          name: Print the working directory
          command: pwd
      - run:
          name: Show who am I
          command: whoami
      - restore_cache:
          keys:
            - market-reporter-{{ checksum "environment-fixed.yaml" }}
      - run:
          name: Create an environment
          command: |
              conda env create -f environment-fixed.yaml -n circleci --quiet
              conda activate circleci
      - save_cache:
          key: market-reporter-{{ checksum "environment-fixed.yaml" }}
          paths:
            - /opt/conda
            - /opt/reporter/.conda
