
---
- name: install PostgreSQL
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  become: yes
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2
- name: start and enable PostgreSQL
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes
- name: create a user
  postgresql_user:
    name: "{{ ansible_user }}"
    state: present
    role_attr_flags: CREATEDB,CREATEROLE
  become: yes
  become_user: postgres
- name: create a database file
  postgresql_db:
    name: "{{ db_name }}"
    login_user: "{{ ansible_user }}"
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    encoding: UTF-8
    template: template0
...
