---
- name: get vpc_id
  ec2_vpc_net_facts:
    region: "{{ ec2_config.region }}"
    filters:
      "tag:Name": "{{ ec2_config.vpc_name }}"
  register: vpc_net_fact
  check_mode: no

- name: get subnet_id
  ec2_vpc_subnet_facts:
    region: "{{ ec2_config.region }}"
    filters:
      vpc-id: "{{ vpc_net_fact.vpcs[0].id }}"
  register: subnet_fact

- name: create security group
  ec2_group:
    name: "{{ ec2_config.security_group_name }}"
    description: "SSH Only"
    vpc_id: "{{ subnet_fact.subnets[0].vpc_id }}"
    state: "present"
    region: "{{ ec2_config.region }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "0.0.0.0/0"
  register: security_group

- name: create an instance
  ec2:
    image: "{{ ec2_config.image }}"
    wait: true
    region: "{{ ec2_config.region }}"
    group_id: "{{ security_group.group_id }}"
    key_name: "{{ (ansible_ssh_private_key_file | basename | splitext)[0] }}"
    vpc_subnet_id: "{{ subnet_fact.subnets[0].id }}"
    volumes:
      - device_name: /dev/xvda
        volume_size: "{{ ec2_config.volume_size }}"
    instance_tags:
      Name: "{{ec2_config.instance_name }}"
    assign_public_ip: yes
    instance_type: "{{ ec2_config.instance_type }}"
  register: ec2

- name: wait for ssh connection
  wait_for:
    port: 22
    host: "{{ item.public_ip }}"
    timeout: 300
    state: started
  with_items: "{{ ec2.instances }}"

- name: add new instance to host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: launched
  with_items: "{{ ec2.instances }}"
...
